### ISSUE TITLE
Action gives up once it meets a failed PR

### ISSUE THREAD

**Issue by gregtyler** [koj-co/dependabot-pr-action#70]
We have multiple dependabot PRs on our repo, something like this:
- #1013, status checks have passed
- #1014, status checks have failed
- #1015, status checks have passed

With autoapprove/merge enabled, I would have expected this action to merge both #1013 and #1015. Instead, it has merged #1015 and then failed with the error "All statuses are not success". On subsequent runs, with #1013 and #1014 still unmerged, it continues to give that error.

I think the issue here is in [line 80 of index.ts](https://github.com/koj-co/dependabot-pr-action/blob/b49ffa0e535a3363a3dfb65e298a1276de9ad4ea/src/index.ts#L80). If it finds an unsuccessful status here it uses `break` to cancel the entire for loop, so no more PRs are processed. I think it should instead use `continue` like [line 66](https://github.com/koj-co/dependabot-pr-action/blob/b49ffa0e535a3363a3dfb65e298a1276de9ad4ea/src/index.ts#L66), where it finds and unsuccessful check.

I'm happy to raise a PR to change this, but wanted to check first because I'm not sure if this difference is intentional.

**Comment by AnandChowdhary** [comment]
You're right, it should be `continue` instead. Happy to accept a PR!

**Comment by gregtyler** [comment]
Thanks Anand, I've created #71 :)
